### ISSUE TITLE
Playbook execution terminates with fatal error at certbot role

### ISSUE THREAD

**Issue by techzilla** [while-true-do/ansible-role-certbot#7]
### Type of Report

bug

### Actual behaviour

Play terminates after task has fatal error.

```
TASK [certbot : Include "standalone" Creation Tasks] **************************************************************************************************
fatal: [D047ADF6.ptr.provps.com]: FAILED! => {"msg": "The conditional check 'wtd_certbot_create_method' failed. The error was: error while evaluating conditional (wtd_certbot_create_method): 'standalone' is undefined\n\nThe error appears to have been in '/run/media/username/archive/Projects/playbook-project/required-roles/certbot/tasks/main.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Include \"{{ wtd_certbot_create_method }}\" Creation Tasks\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

```

### Expected behaviour

Amusing intended behavior is to execute the task when `wtd_certbot_create_method` is defined.

### Specifications

Executing from a playbook's repository pipenv, 
ansible 2.7.0
  config file = /run/media/username/archive/Projects/playbook-project/ansible.cfg
  configured module search path = ['/run/media/username/archive/Projects/playbook-project/library']
  ansible python module location = /home/username/.local/share/virtualenvs/playbook-project-AjUj67dc/lib/python3.6/site-packages/ansible
  executable location = /home/username/.local/share/virtualenvs/playbook-project-AjUj67dc/bin/ansible
  python version = 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]

**Comment by techzilla** [comment]
I was able to get the expected behavior by making all the error generating when conditions check `variable is defined`.

I forked the repo, since I could identify no project git branching convention or workflow, I just committed to the forked Master.

https://github.com/techzilla/ansible-role-certbot

**Comment by daniel-schier** [comment]
Hey,

thanks a lot for the findings.
Would be awesome, if you can open up a pull request according to the Contribution Guidelines.

**Comment by daniel-schier** [comment]
Opend PR myself for the commits you've done in your fork.
Thanks a lot! :+1:

**Comment by daniel-schier** [comment]
seems like github is having some bugs displaying the pr

**Comment by daniel-schier** [comment]
@techzilla thanks a lot again for pointing this out. ;)
